set(_CATKIN_CURRENT_PACKAGE "slam_test")
set(slam_test_VERSION "0.0.0")
set(slam_test_MAINTAINER "tanmay <tanmay@todo.todo>")
set(slam_test_PACKAGE_FORMAT "2")
set(slam_test_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "cv_bridge" "image_transport" "message_generation")
set(slam_test_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "cv_bridge")
set(slam_test_BUILDTOOL_DEPENDS "catkin")
set(slam_test_BUILDTOOL_EXPORT_DEPENDS )
set(slam_test_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "cv_bridge" "image_transport" "message_generation")
set(slam_test_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "cv_bridge" "image_transport" "message_generation")
set(slam_test_TEST_DEPENDS )
set(slam_test_DOC_DEPENDS )
set(slam_test_URL_WEBSITE "")
set(slam_test_URL_BUGTRACKER "")
set(slam_test_URL_REPOSITORY "")
set(slam_test_DEPRECATED "")